### PR TITLE
add a failing test that i'm not quite sure how to fix

### PR DESCRIPTION
**Pull request by chadaustin**
Hi @jrburke. Rather than filing a GitHub issue I'm filing a PR adding a test that currently fails.  I'm not quite sure how to make this use case work. Do you think you could help describe what code change is necessary here?

cc @dgoldstein0

### CODE REVIEW

**Comment by chadaustin** [comment]
Added a fix that makes the test pass.  Not 100% sure it's right.

**Comment by dgoldstein0** [comment]
*headscratch*

Is this really the problem?  I thought in our code we expected

```
define("a", [] function(){...});
require(["a"], function(a){console.log(a)});
```

to work, (and load "a" into the context of `require`), but not that we could synchronously require something we just `define`d.  Of course it would be nice to allow that, but I don't recall requirejs supporting that so I'm skeptical that's the actual problem here.  Maybe your fix has some other side effects?

**Comment by chadaustin** [comment]
Actually neither seem to work in what I was trying earlier, but I haven't reduced the other case to a test yet.  :/

**Comment by jrburke** [comment]
Right, this is not designed to work in requirejs or alameda. The async `require(["a"], function(){})` is the way to bring 'a' into being.

Going to close as current code working as designed.

**Pull request closed without merging**
